"use client"

import { useEffect, useMemo, useState } from "react"
import type { AgentDashboardData } from "@/lib/agent-dashboard"
import { useEventSetup } from "@/lib/event-store"
import { Blobs } from "@/components/blobs"
import { DashboardSidebar } from "@/components/dashboard/sidebar"
import { StatCards } from "@/components/dashboard/stat-cards"
import { CountdownMessages } from "@/components/dashboard/countdown-messages"
import { BudgetBreakdown } from "@/components/dashboard/budget-breakdown"
import { ChatPanel } from "@/components/dashboard/chat-panel"
import { SupplierGrid } from "@/components/dashboard/supplier-grid"
import { BrandingKit } from "@/components/dashboard/branding-kit"
import { daysUntil, formatDate, readEventId, setupToDashboardData, type EventSetup } from "@/lib/event-store"

function dashboardEventToSetup(data: AgentDashboardData): EventSetup {
  return {
    name: data.event.name,
    description: data.event.description,
    instagram: data.event.instagram,
    attendance: String(data.event.expectedAttendance || ""),
    budget: String(data.budget.totalBudget || ""),
    date: data.event.date,
  }
}

export default function DashboardPage() {
  const { setup, loaded } = useEventSetup()
  const [dashboardData, setDashboardData] = useState<AgentDashboardData | null>(null)
  const [fetching, setFetching] = useState(false)
  const [fetchError, setFetchError] = useState<string | null>(null)

  useEffect(() => {
    if (!loaded) return

    const urlEventId = new URLSearchParams(window.location.search).get("event_id")
    const eventId = urlEventId || readEventId()
    if (!eventId) return

    const controller = new AbortController()
    setFetching(true)
    setFetchError(null)

    fetch(`/api/events/${eventId}`, { signal: controller.signal })
      .then(async (response) => {
        const data = await response.json()
        if (!response.ok) throw new Error(data.error || "Could not load saved agent dashboard.")
        setDashboardData(data as AgentDashboardData)
      })
      .catch((error) => {
        if (error.name === "AbortError") return
        setFetchError(error instanceof Error ? error.message : "Could not load saved agent dashboard.")
      })
      .finally(() => setFetching(false))

    return () => controller.abort()
  }, [loaded])

  const fallbackData = useMemo(() => setupToDashboardData(setup), [setup])
  const data = dashboardData ?? fallbackData
  const widgetSetup = dashboardEventToSetup(data)
  const days = daysUntil(widgetSetup.date)

  const now = new Date()
  const timeLabel = now.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" })
  const dateLabel = now.toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "short" })

  return (
    <div className="relative min-h-screen bg-background">
      <Blobs className="absolute" />

      <div className="relative z-10 flex">
        <DashboardSidebar />

        <main className="flex-1 px-4 py-6 sm:px-6 lg:px-8">
          {/* Top bar */}
          <header className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <h1 className="text-balance text-2xl font-bold leading-tight text-foreground sm:text-3xl">
                Your {data.event.name} agent dashboard is ready
              </h1>
              <p className="mt-1 text-sm text-muted-foreground">
                Budget allocation is generated by the first HeyComms tool. Tweak anything in chat.
              </p>
            </div>
            <div className="flex items-center gap-3 rounded-full border border-hairline bg-card px-4 py-2">
              <span className="tabular-nums text-sm text-foreground">{timeLabel}</span>
              <span className="size-1 rounded-full bg-muted-foreground" aria-hidden="true" />
              <span className="text-xs text-muted-foreground">{dateLabel}</span>
            </div>
          </header>

          {(fetching || fetchError) && (
            <div className="mt-4 rounded-2xl border border-hairline bg-card px-4 py-3 text-sm text-muted-foreground">
              {fetching
                ? "Loading saved agent output..."
                : `Using local preview data because the saved dashboard could not load: ${fetchError}`}
            </div>
          )}

          {/* Stat cards */}
          <div id="overview" className="mt-6 scroll-mt-6">
            <StatCards event={data.event} budget={data.budget} days={days} />
          </div>

          {/* Middle row */}
          <div id="comms" className="mt-6 grid scroll-mt-6 grid-cols-1 gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_380px]">
            <CountdownMessages setup={widgetSetup} />
            <BudgetBreakdown budget={data.budget} />
            <ChatPanel setup={widgetSetup} budget={data.budget} />
          </div>

          {/* Bottom row */}
          <div className="mt-6 grid grid-cols-1 gap-5 lg:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)]">
            <section id="suppliers" className="scroll-mt-6">
              <SupplierGrid />
            </section>
            <section id="branding" className="scroll-mt-6">
              <BrandingKit setup={widgetSetup} dateLabel={formatDate(widgetSetup.date)} />
            </section>
          </div>
        </main>
      </div>
    </div>
  )
}
